# Generated by Django 5.0.7 on 2024-09-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
