# Generated by Django 5.0.7 on 2024-09-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registeredplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateRecognitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('recognized_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recognized_at'],
            },
        ),
    ]
