# Generated by Django 5.0.7 on 2024-09-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registeredplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredplate',
            old_name='ocupation',
            new_name='occupation',
        ),
    ]
