# Generated by Django 5.0.7 on 2024-10-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_registeredplate_color_registeredplate_dependence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platerecognitionrecord',
            name='color',
            field=models.CharField(default='desconocido', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platerecognitionrecord',
            name='dependence',
            field=models.CharField(default='desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platerecognitionrecord',
            name='model',
            field=models.CharField(default='desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platerecognitionrecord',
            name='phone',
            field=models.CharField(default='desconocido', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platerecognitionrecord',
            name='voucher',
            field=models.CharField(default='desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
